Facebook/railsbook-master/config/routes.rb
Facebook::Application.routes.draw do

    devise_for :users

    root to: 'home#index'
    match 'follow' => 'users#follow'
    match 'unfollow' => 'users#unfollow'
    match 'like' => 'users#like'
    match 'unlike' => 'users#unlike'

    resources :users
    resources :posts
    resources :comments

end

Facebook/railsbook-master/app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :user
    belongs_to :post
    attr_accessible :content, :post_id
    acts_as_likeable
    include PublicActivity::Model
    tracked owner: ->(controller, model) { controller && controller.current_user }
end

Facebook/railsbook-master/app/models/follow.rb
class Follow < ActiveRecord::Base
    acts_as_follow_store
end

Facebook/railsbook-master/app/models/like.rb
class Like < ActiveRecord::Base
    acts_as_like_store
    include PublicActivity::Model
    tracked owner: ->(controller, model) { controller && controller.current_user }
end

Facebook/railsbook-master/app/models/mention.rb
class Mention < ActiveRecord::Base
  acts_as_mention_store
end

Facebook/railsbook-master/app/models/post.rb
class Post < ActiveRecord::Base
    attr_accessible :content, :user_id, :avatar
    belongs_to :user
    has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "avatar/missing.jpg"
    has_many :comments
    include PublicActivity::Model
    tracked owner: ->(controller, model) { controller && controller.current_user }
    acts_as_likeable
end

Facebook/railsbook-master/app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable

    # Setup accessible (or protected) attributes for your model
    attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :avatar
    validates :name, presence: true
    # attr_accessible :title, :body
    acts_as_followable
    acts_as_follower
    has_many :posts
    has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "50x50>" }, :default_url => "avatar/missing.jpg"
    has_many :comments
    acts_as_liker
end

Facebook/railsbook-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include PublicActivity::StoreController
  # ...
   hide_action :current_user
end

Facebook/railsbook-master/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_filter :authenticate_user!, only: [:create, :destroy]
    def create
        @post = Post.find(params[:comment][:post_id])
        @comment = Comment.new(params[:comment])
        @comment.user = current_user
        @comment.save
        redirect_to @post
    end
    
end

Facebook/railsbook-master/app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        unless user_signed_in?
            redirect_to new_user_session_path
        else
        @post = Post.new
        followees_ids = current_user.followees(User).pluck(:id)
        #get only the ids of the people current_user folllows
        #followees_ids << current_user.id
        @activities = PublicActivity::Activity.where(owner_id: followees_ids, owner_type: "User")
        end
    end

end

Facebook/railsbook-master/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    # GET /posts
    # GET /posts.json

    before_filter :authenticate_user!, only: [:create, :new, :edit, :destroy]
    def index
        @posts = current_user.posts

        respond_to do |format|
            format.html # index.html.erb
            format.json { render json: @posts }
        end
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
        @comment = Comment.new
        @post = Post.find(params[:id])
        @comments = @post.comments

        respond_to do |format|
            format.html # show.html.erb
            format.json { render json: @post }
        end
    end

    # GET /posts/new
    # GET /posts/new.json
    def new
        @post = Post.new

        respond_to do |format|
            format.html # new.html.erb
            format.json { render json: @post }
        end
    end

    # GET /posts/1/edit
    def edit
        @post = Post.find(params[:id])
    end

    # POST /posts
    # POST /posts.json
    def create
        @post = Post.new(params[:post])
        @post.user = current_user

        respond_to do |format|
            if @post.save
                format.html { redirect_to @post, notice: 'Post was successfully created.' }
                format.json { render json: @post, status: :created, location: @post }
            else
                format.html { render action: "new" }
                format.json { render json: @post.errors, status: :unprocessable_entity }
            end
        end
    end

    # PUT /posts/1
    # PUT /posts/1.json
    def update
        @post = Post.find(params[:id])

        respond_to do |format|
            if @post.update_attributes(params[:post])
                format.html { redirect_to @post, notice: 'Post was successfully updated.' }
                format.json { head :no_content }
            else
                format.html { render action: "edit" }
                format.json { render json: @post.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
        @post = Post.find(params[:id])
        @post.destroy

        respond_to do |format|
            format.html { redirect_to posts_url }
            format.json { head :no_content }
        end
    end
end

Facebook/railsbook-master/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @activities = PublicActivity::Activity.where(owner_id: @user.id, owner_type: "User")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  def follow
  	@user = User.find(params[:user])
	current_user.follow!(@user)
  end
  def unfollow
  	@user = User.find(params[:user])
	current_user.unfollow!(@user)
  end
  def like
      if params[:likeable_type] == "Post"
          @likeable = Post.find(params[:likeable_id])
      else
          @likeable = Comment.find(params[:likeable_id])
      end
	current_user.like!(@likeable)
  end
  def unlike
      if params[:likeable_type] == "Post"
          @likeable = Post.find(params[:likeable_id])
      else
          @likeable = Comment.find(params[:likeable_id])
      end
	current_user.unlike!(@likeable)
  end
end

Facebook/railsbook-master/app/helpers/application_helper.rb
module ApplicationHelper
end

Facebook/railsbook-master/app/helpers/comments_helper.rb
module CommentsHelper
end

Facebook/railsbook-master/app/helpers/home_helper.rb
module HomeHelper
end

Facebook/railsbook-master/app/helpers/posts_helper.rb
module PostsHelper
end

Facebook/railsbook-master/app/helpers/users_helper.rb
module UsersHelper
end

Facebook/railsbook-master/app/views/home/index.html.erb
<%= render 'posts/form' %>
<% @activities.each do |activity| %>
    <%= render_activity(activity) %>
<% end %>

Facebook/railsbook-master/app/views/layouts/_header.html.erb
<nav class="top-bar">
<ul class="title-area">
    <li class="name">
    <h1><a href="/">Rails book</a></h1>
    </li>
    <li class="toggle-topbar menu-icon">

    <a href="#">Menu</a>
    </li>
</ul>
<section class="top-bar-section">
<%if user_signed_in? %>
    <ul class="right">
        <li><%= link_to 'Users', users_path %> </li>
        <li class="divider"></li>
        <li><%= link_to 'Profile', current_user %> </li>
        <li class="divider"></li>
        <li><%= link_to 'Edit', edit_user_registration_path %></li>
        <li class="divider"></li>
        <li><%= link_to 'Sign out', destroy_user_session_path , method: :delete %></li>
    </ul>
<% end %>
</section>
</nav>

Facebook/railsbook-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
	<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
		<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
			<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
				<head>
					<meta charset="utf-8" />

					<!-- Uncomment to make IE8 render like IE7 -->
					<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

					<!-- Set the viewport width to device width for mobile -->
					<meta name="viewport" content="width=device-width, initial-scale=1.0" />

					<title><%= content_for?(:title) ? yield(:title) : "Railsbook" %></title>

					<%= stylesheet_link_tag    "application" %>
					<%= javascript_include_tag "vendor/custom.modernizr" %>
					<%= csrf_meta_tags %>
				</head>

				<body>

						<%= render 'layouts/header' %>
					<div class="row">
                        <% if notice %>
						<p class="alert-box success"><%= notice %></p>
                    <% end %>
                    <% if alert %>
						<p class="alert-box error"><%= alert %></p>
                    <% end %>
						<div class="large-8 columns">

							<%= yield %>
						</div>
					</div>


					<%= javascript_include_tag "application" %>
				</body>
			</html>

Facebook/railsbook-master/app/views/public_activity/comment/_create.html.erb
<% if activity.trackable %>
<div class="user-box">
<%= image_tag activity.owner.avatar.url(:thumb), class: 'like_profile' %>
<%= link_to activity.owner.name, activity.owner %>

commented on <%= link_to "Post", activity.trackable.post %>

</div>
<div class="like_post">
<%= render 'comments/comment', comment: activity.trackable%>
</div>
<% end %>

Facebook/railsbook-master/app/views/public_activity/like/_create.html.erb
<% if activity.trackable %>
<div class="user-box">
<%= image_tag activity.owner.avatar.url(:thumb), class: 'like_profile' %>
<%= link_to activity.owner.name, activity.owner %>

liked a <%= link_to activity.trackable.likeable.class, activity.trackable.likeable %>
</div>
<div class="like_post">
<%= render 'posts/post', post: activity.trackable.likeable %>
</div>
<% end %>

Facebook/railsbook-master/app/views/shared/_follow.html.erb
<%= button_to "Follow", follow_path(user: user.id) , remote: true, method: :get , class: "small button" %>

Facebook/railsbook-master/app/views/shared/_follow_form.html.erb
<% if current_user!= user %>
	<div class="user-<%= user.id %>">

		<div id="follow_form">
			<% if current_user.follows?(user) %>
				<%= render 'shared/unfollow', user: user %>
			<% else %>
				<%= render 'shared/follow', user: user %>
			<% end %>
		</div>
	</div>
<% end %>

Facebook/railsbook-master/app/views/shared/_form.html.erb
<%= form_for @comment do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :post_id, value: @post.id %>

  <div class="field">
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit class: 'small button' %>
  </div>
<% end %>

Facebook/railsbook-master/app/views/shared/_like.html.erb
<%= link_to "like", like_path(likeable_id: likeable.id, likeable_type: likeable.class) , remote: true, method: :get , class: "like" %>

Facebook/railsbook-master/app/views/shared/_like_form.html.erb
<% if user_signed_in? %>

		<div id="like_form">
			<% if current_user.likes?(likeable) %>
				<%= render 'shared/unlike', likeable: likeable %>
			<% else %>
				<%= render 'shared/like', likeable: likeable  %>
			<% end %>
	</div>
<% end %>

Facebook/railsbook-master/app/views/shared/_unfollow.html.erb
<%= button_to "UnFollow", unfollow_path(user: user.id), remote: true, method: :get , class: 'small button' %>

Facebook/railsbook-master/app/views/shared/_unlike.html.erb
<%= link_to "Unlike", unlike_path(likeable_id: likeable.id, likeable_type: likeable.class ), remote: true, method: :get , class: 'unlike' %>

Facebook/railsbook-master/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Facebook/railsbook-master/app/views/users/_user.html.erb
<div class="row">
<div class="user-box user">
<div class="right"><%= render 'shared/follow_form', user: user %></div>
<%= image_tag user.avatar.url(:thumb), class: 'profile' %>
<%= link_to user.name, user %>
</div>
    
</div>

Facebook/railsbook-master/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

Facebook/railsbook-master/app/views/users/follow.js.erb
$('.user-<%= @user.id %> > #follow_form').html("<%= escape_javascript(render 'shared/unfollow', user: @user) %>")

Facebook/railsbook-master/app/views/users/index.html.erb
<%= render @users %>

Facebook/railsbook-master/app/views/users/like.js.erb
$('.<%= @likeable.class %>-<%= @likeable.id %> > #like_form').html("<%= escape_javascript(render 'shared/unlike', likeable: @likeable) %>")
$('.<%= @likeable.class %>-<%= @likeable.id %> > .likes').html("<%= pluralize(@likeable.likers(User).count, 'like')%>")

Facebook/railsbook-master/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

Facebook/railsbook-master/app/views/users/show.html.erb
<div class="right">
<% if user_signed_in? %>
<%= render 'shared/follow_form' , user: @user%>
<% end %>
</div>
<%= image_tag @user.avatar.url(:thumb), class: 'profile' %>
<span class="left">
<h4><%= @user.name %></h4>
</span>
<div class="row feed ">
<% @activities.each do |activity| %>
    <%= render_activity(activity) %>
<% end %>
</div>

Facebook/railsbook-master/app/views/users/unfollow.js.erb
$('.user-<%= @user.id %> > #follow_form').html("<%= escape_javascript(render 'shared/follow', user: @user) %>")

Facebook/railsbook-master/app/views/users/unlike.js.erb
$('.<%= @likeable.class %>-<%= @likeable.id %> > #like_form').html("<%= escape_javascript(render 'shared/like', likeable: @likeable) %>")
$('.<%= @likeable.class %>-<%= @likeable.id %> > .likes').html("<%= pluralize(@likeable.likers(User).count, 'like')%>")